routes/web.php
<?php

use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UmumController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('xss')->group(function () {

    // Route::get('/buat-kalender', [ParsingController::class, 'buat_kalender']);
    Route::any('/', [LandingPageController::class, 'index'])->name('/');
    Route::any('/login', [LoginController::class, 'index'])->name('login');

    Route::middleware(['auth'])->group(function () {
        Route::prefix('auth')->group(function () {
            Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::post('/ajax-dashboard', [HomeController::class, 'ajax'])->name('ajax-dashboard');
            Route::any('/profil', [UserController::class, 'profil'])->name('profil');
            Route::post('/ganti-foto', [UserController::class, 'ganti_foto'])->name('ganti-foto');
            Route::post('/simpan-foto', [UserController::class, 'simpan_foto'])->name('simpan-foto');
            Route::any('/password', [UserController::class, 'password'])->name('password');
            Route::post('/ganti-password', [UserController::class, 'ganti_password'])->name('ganti-password');
            Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
            Route::any('/weblog', [LogController::class, 'index'])->name('aktivitas');
            Route::get('/force-login/{id}', [LoginController::class, 'force_login'])->name('force-login');
            Route::get('/back-login/{id}', [LoginController::class, 'back_login'])->name('back-login');

            // Master Data
            // Product
            Route::resource('product', ProductController::class);
            Route::post('/ajax-product', [ProductController::class, 'ajax'])->name('ajax-product');
            Route::post('/product-ganti-foto', [ProductController::class, 'ganti_foto'])->name('product-ganti-foto');

            // Company
            Route::resource('company', CompanyController::class);
            Route::post('/ajax-company', [CompanyController::class, 'ajax'])->name('ajax-company');
            Route::post('/company-ganti-foto', [CompanyController::class, 'ganti_foto'])->name('company-ganti-foto');

            // Setting
            Route::resource('umum', UmumController::class);
            Route::resource('user', UserController::class);
            Route::post('/ajax-user', [UserController::class, 'ajax'])->name('ajax-user');

            Route::resource('role', RoleController::class);
            Route::post('/ajax-role', [RoleController::class, 'ajax'])->name('ajax-roles');
            Route::resource('permission', PermissionController::class);
            Route::post('/ajax-permission', [PermissionController::class, 'ajax'])->name('ajax-permission');

            // Banner
            Route::resource('banner', BannerController::class);
            Route::post('/ajax-banner', [BannerController::class, 'ajax'])->name('ajax-banner');
            Route::post('/banner-ganti-foto', [BannerController::class, 'ganti_foto'])->name('banner-ganti-foto');

            // about
            Route::resource('about', AboutController::class);

            // ajax
            Route::prefix('ajax')->group(function () {
                Route::post('/role', [AjaxController::class, 'role'])->name('drop-role');
                Route::post('/company', [AjaxController::class, 'company'])->name('drop-company');
                Route::post('/group', [AjaxController::class, 'group'])->name('drop-group');
                Route::post('/examtype', [AjaxController::class, 'examtype'])->name('drop-examtype');
                Route::post('/method', [AjaxController::class, 'method'])->name('drop-method');
                Route::post('/grade', [AjaxController::class, 'grade'])->name('drop-grade');
                Route::post('/fase', [AjaxController::class, 'fase'])->name('drop-fase');
                Route::post('/exam', [AjaxController::class, 'exam'])->name('drop-exam');
                Route::post('/room', [AjaxController::class, 'room'])->name('drop-room');
                Route::post('/surveillancetype', [AjaxController::class, 'surveillancetype'])->name('drop-surveillancetype');
            });
        });
    });
});

resources/views/backend/layouts/footer.blade.php
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
        <div class="mb-2 mb-md-0">
        ©
        <script>
            document.write(new Date().getFullYear());
        </script>
            |
            <a href="https://fernadi.my.id/" target="_blank" class="footer-link fw-bolder">Fernadi</a>
        </div>
    </div>
    </footer>

resources/views/backend/layouts/header.blade.php
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        {{ $tanggal_sekarang }}
        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <!-- Place this tag where you want the button to render. -->

            @if (session()->has('loginAs'))
                <span class="badge bg-danger">Login As : {{ Auth::user()->nama }}</span>
            @endif

            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        <img src="{{ Auth::user()->foto === null || Auth::user()->foto == '' ? asset('backend/sneat-1.0.0/assets/img/avatars/1.png') : url('storage/foto/thum_' . Auth::user()->foto) }}"
                            alt class="w-px-40 h-px-40 rounded-circle" />
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        <img src="{{ Auth::user()->foto === null || Auth::user()->foto == '' ? asset('backend/sneat-1.0.0/assets/img/avatars/1.png') : url('storage/foto/thum_' . Auth::user()->foto) }}"
                                            alt class="w-px-40 h-px-40 rounded-circle" />
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block">{{ Auth::user()->nama }}</span>
                                    <small class="text-muted">{{ Auth::user()->roles->first()->name }}</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ route('profil') }}">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">Profile</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ route('password') }}">
                            <i class='bx bxs-key me-2'></i>
                            <span class="align-middle">Change Password</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ route('aktivitas') }}">
                            <span class="d-flex align-items-center align-middle">
                                <i class="flex-shrink-0 bx bx-bar-chart me-2"></i>
                                <span class="flex-grow-1 align-middle">Activity</span>
                            </span>
                        </a>
                    </li>
                    @if (session()->has('loginAs'))
                        <li>
                            <a class="dropdown-item" href="{{ route('back-login', ['id' => session('loginID')]) }}" id="btn-logout">
                                <i class='bx bxs-arrow-to-left text-danger'></i>
                                <span class="align-middle text-danger">Exit from LoginAs</span>
                            </a>
                        </li>
                    @endif
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}" id="btn-logout">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Logout</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul>
    </div>
</nav>

resources/views/backend/layouts/layout.blade.php
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="{{ asset('backend/sneat-1.0.0/') }}/assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>{{ $title_web }}</title>

    <meta name="description" content="" />
    <link rel="shortcut icon"  href="{{ $favicon }}" />

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            @include('backend.layouts.sidebar')

            <!-- Layout container -->
            <div class="layout-page">
                @include('backend.layouts.header')

                <div class="content-wrapper">

                    @yield('konten')

                    @include('backend.layouts.footer')

                    <div class="content-backdrop fade"></div>
                </div>

            </div>

      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    @csrf

    {{-- @viteReactRefresh
    @vite('resources/js/app.jsx') --}}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/js/helpers.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/js/bootstrap.js"></script>
    <script src="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="{{ asset('backend/sneat-1.0.0/') }}/assets/vendor/js/menu.js"></script>
    <script src="{{ asset('backend/sneat-1.0.0/') }}/assets/js/main.js"></script>

    {{-- bootstrap-select --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    {{-- end bootstrap-select --}}

    @yield('script', '')

  </body>
</html>

resources/views/backend/layouts/sidebar.blade.php
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="{{ route('dashboard') }}" class="app-brand-link">
            <h3 class="">{!! $logo !!}</h3>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    {{-- <div class="menu-inner-shadow"></div> --}}

    <ul class="menu-inner py-1 mt-2">
        <!-- Dashboard -->
        <li class="menu-item {{ menuAktif('dashboard') }}">
            <a href="{{ route('dashboard') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-pie-chart-alt-2"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>

        <!-- Master Data -->
        {{-- <li class="menu-header small text-uppercase"><span class="menu-header-text">Master Data</span></li> --}}
        @permission('product-read')
            <li class="menu-item {{ menuAktif('product') }}">
                <a href="{{ route('product.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-package"></i>
                    <div data-i18n="Analytics">Product</div>
                </a>
            </li>
        @endpermission

        @permission('company-read')
            <li class="menu-item {{ menuAktif('company') }}">
                <a href="{{ route('company.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-buildings"></i>
                    <div data-i18n="Analytics">Company</div>
                </a>
            </li>
        @endpermission

        @permission('user-read', 'role-read', 'permission-read')
            {{-- <li class="menu-header small text-uppercase"><span class="menu-header-text">Web Settings</span></li> --}}
            <li class="menu-item {{ menuAktif(['user', 'role', 'permission']) }}">
                <a href="#" class="menu-link menu-toggle">
                    <i class='menu-icon tf-icons bx bx-user-circle'></i>
                    <div data-i18n="Form Layouts">Userweb</div>
                </a>
                <ul class="menu-sub">
                    @permission('user-read')
                        <li class="menu-item {{ menuAktif('user') }}">
                            <a href="{{ route('user.index') }} " class="menu-link">
                                <div data-i18n="Vertical Form">User</div>
                            </a>
                        </li>
                    @endpermission
                    @permission('role-read')
                        <li class="menu-item {{ menuAktif('role') }}">
                            <a href="{{ route('role.index') }}" class="menu-link">
                                <div data-i18n="Horizontal Form">Role</div>
                            </a>
                        </li>
                    @endpermission
                    @permission('permission-read')
                        <li class="menu-item {{ menuAktif('permission') }}">
                            <a href="{{ route('permission.index') }}" class="menu-link">
                                <div data-i18n="Horizontal Form">Permission</div>
                            </a>
                        </li>
                    @endpermission
                </ul>
            </li>
        @endpermission

        @permission('banner-read')
            <li class="menu-item {{ menuAktif('banner') }}">
                <a href="{{ route('banner.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-tab"></i>
                    <div data-i18n="Analytics">Banner</div>
                </a>
            </li>
        @endpermission

        @permission('about-read')
            <li class="menu-item {{ menuAktif('about') }}">
                <a href="{{ route('about.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-info-circle"></i>
                    <div data-i18n="Analytics">About</div>
                </a>
            </li>
        @endpermission

        @permission('umum-read')
            <li class="menu-item {{ menuAktif('umum') }}">
                <a href="{{ route('umum.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-cog"></i>
                    <div data-i18n="Analytics">Setting</div>
                </a>
            </li>
        @endpermission


    </ul>
</aside>