routes/web.php
<?php

use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UmumController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('xss')->group(function () {

    // Route::get('/buat-kalender', [ParsingController::class, 'buat_kalender']);
    Route::any('/', [LandingPageController::class, 'index'])->name('/');
    Route::any('/login', [LoginController::class, 'index'])->name('login');

    Route::middleware(['auth'])->group(function () {
        Route::prefix('auth')->group(function () {
            Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::post('/ajax-dashboard', [HomeController::class, 'ajax'])->name('ajax-dashboard');
            Route::any('/profil', [UserController::class, 'profil'])->name('profil');
            Route::post('/ganti-foto', [UserController::class, 'ganti_foto'])->name('ganti-foto');
            Route::post('/simpan-foto', [UserController::class, 'simpan_foto'])->name('simpan-foto');
            Route::any('/password', [UserController::class, 'password'])->name('password');
            Route::post('/ganti-password', [UserController::class, 'ganti_password'])->name('ganti-password');
            Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
            Route::any('/weblog', [LogController::class, 'index'])->name('aktivitas');
            Route::get('/force-login/{id}', [LoginController::class, 'force_login'])->name('force-login');
            Route::get('/back-login/{id}', [LoginController::class, 'back_login'])->name('back-login');

            // Master Data
            // Product
            Route::resource('product', ProductController::class);
            Route::post('/ajax-product', [ProductController::class, 'ajax'])->name('ajax-product');
            Route::post('/product-ganti-foto', [ProductController::class, 'ganti_foto'])->name('product-ganti-foto');

            // Company
            Route::resource('company', CompanyController::class);
            Route::post('/ajax-company', [CompanyController::class, 'ajax'])->name('ajax-company');
            Route::post('/company-ganti-foto', [CompanyController::class, 'ganti_foto'])->name('company-ganti-foto');

            // Setting
            Route::resource('umum', UmumController::class);
            Route::resource('user', UserController::class);
            Route::post('/ajax-user', [UserController::class, 'ajax'])->name('ajax-user');

            Route::resource('role', RoleController::class);
            Route::post('/ajax-role', [RoleController::class, 'ajax'])->name('ajax-roles');
            Route::resource('permission', PermissionController::class);
            Route::post('/ajax-permission', [PermissionController::class, 'ajax'])->name('ajax-permission');

            // Banner
            Route::resource('banner', BannerController::class);
            Route::post('/ajax-banner', [BannerController::class, 'ajax'])->name('ajax-banner');
            Route::post('/banner-ganti-foto', [BannerController::class, 'ganti_foto'])->name('banner-ganti-foto');

            // about
            Route::resource('about', AboutController::class);

            // ajax
            Route::prefix('ajax')->group(function () {
                Route::post('/role', [AjaxController::class, 'role'])->name('drop-role');
                Route::post('/company', [AjaxController::class, 'company'])->name('drop-company');
                Route::post('/group', [AjaxController::class, 'group'])->name('drop-group');
                Route::post('/examtype', [AjaxController::class, 'examtype'])->name('drop-examtype');
                Route::post('/method', [AjaxController::class, 'method'])->name('drop-method');
                Route::post('/grade', [AjaxController::class, 'grade'])->name('drop-grade');
                Route::post('/fase', [AjaxController::class, 'fase'])->name('drop-fase');
                Route::post('/exam', [AjaxController::class, 'exam'])->name('drop-exam');
                Route::post('/room', [AjaxController::class, 'room'])->name('drop-room');
                Route::post('/surveillancetype', [AjaxController::class, 'surveillancetype'])->name('drop-surveillancetype');
            });
        });
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $table = 'companies';
    protected $primaryKey = 'id';
    public $timestamps = false;

    public function userinput()
    {
        return $this->belongsTo(User::class, 'user_input');
    }
    public function userupdate()
    {
        return $this->belongsTo(User::class, 'user_update');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Exports\CompanyExport;
use App\Facade\Weblog;
use App\Models\Company;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Facades\DataTables;
use Laratrust\LaratrustFacade as Laratrust;
use Maatwebsite\Excel\Facades\Excel;
use Proengsoft\JsValidation\Facades\JsValidatorFacade as JSvalidation;
use Intervention\Image\Facades\Image;
use App\Models\User;

class CompanyController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:company-read')->only('index');
        $this->middleware('permission:company-create')->only(['create', 'store']);
        $this->middleware('permission:company-update')->only(['edit', 'update']);
        $this->middleware('permission:company-delete')->only('delete');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.company.index');
    }

    public function ajax(Request $request)
    {
        // filter
        $cari = $request->cari;
        // $tipe = $request->tipe;

        // set query
        $data = Company::query()
            ->with('userinput')
            ->with('userupdate')
            ->when($cari, fn ($e, $cari) => $e->where(function ($e) use ($cari) {
                $e->where('company_code', 'like', '%' . $cari . '%')->orWhere('company_name', 'like', '%' . $cari . '%');
            }))
            ->where('status', $request->status)
            ->orderBy('id','asc');

        // if export
        if ($request->method() === 'POST' && $request->filled('export')) {
            return Excel::download(new CompanyExport($data->get()), 'COMPANY.xlsx');
        }
        // dd($data->get()->toArray());

        // create datatable
        return DataTables::eloquent($data)
            ->addColumn('logo_mod', function ($e) {
                $logo = ($e->logo === "" || $e->logo === null) ? '/storage/company/photo.png' : '/storage/company/' . $e->logo;
                return '<a href="' . url($logo) . '" data-title="' . $e->company_name . '" style="height:50px; overflow:hidden; border-radius:4px;" class="detail-foto"><img src="' . url($logo) . '" class="rounded" width="40"/></a>';
            })
            ->addColumn('time_input_mod', function ($e) {
                $timeInputMod = '
                    <div class="d-flex align-items-center">
                        <b class="text-muted">'. Carbon::parse($e->time_input)->isoFormat('DD MMM YYYY HH:mm') .'</b>
                    </div>
                    <span class="text-muted font-12">By ' . strtoupper($e->userinput->nama) . '</span>
                ';
                return $timeInputMod;
            })
            ->addColumn('time_update_mod', function ($e) {
                if( $e->userupdate ) {
                    $timeUpdateMod = '
                        <div class="d-flex align-items-center">
                            <b class="text-muted">'. Carbon::parse($e->time_update)->isoFormat('DD MMM YYYY HH:mm') .'</b>
                        </div>
                        <span class="text-muted font-12">By ' . strtoupper($e->userupdate->nama) . '</span>
                    ';
                    return $timeUpdateMod;
                } else {
                    return '-';
                }
            })
            ->addColumn('aksi', function ($e) {
                $btnEdit = Laratrust::isAbleTo('company-update') ? '<a href="' . route('company.edit', ['company' => $e->id]) . '" class="btn btn-xs "><i class="bx bx-edit"></i></a>' : '';
                $btnDelete = Laratrust::isAbleTo('company-delete') ?  '<a href="' . route('company.destroy', ['company' => $e->id]) . '" data-title="' . $e->company_name . '" class="btn btn-xs text-danger btn-hapus"><i class="bx bx-trash"></i></a>' : '';
                $btnReload = Laratrust::isAbleTo('company-update') ? '<a href="' . route('company.destroy', ['company' => $e->id]) . '" data-title="' . $e->company_name . '" data-status="' . $e->status . '" class="btn btn-outline-secondary btn-xs btn-hapus"><i class="bx bx-refresh"></i></i></a>' : '';

                if ($e->status == 'y') {
                    return $btnEdit . ' ' . $btnDelete;
                } else {
                    return $btnReload;
                }
            })
            ->rawColumns(['logo_mod','time_input_mod','time_update_mod','aksi'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // validate form
        $validator = JSvalidation::make([
            'code'  => 'required|unique:companies,company_code|min:1',
            'name'  => 'required|min:3',
            'foto' => 'nullable',
        ]);

        // page
        return view('backend.company.create', compact('validator'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate form
        $request->validate([
            'code'  => 'required|unique:companies,company_code|min:1',
            'name'  => 'required|min:3',
            'foto' => 'nullable',
        ]);

        // collect data
        $record = [
            'company_code' => $request->code,
            'company_name' => $request->name,
            'logo' => $request->foto,
            'user_input' => Auth::id(),
        ];

        DB::beginTransaction();
        try {
            // insert data
            Company::create($record);
            DB::commit();

            // create log
            Weblog::set('Create Company : ' . $request->name);

            // redirect index page
            return redirect(route('company.index'))->with(['pesan' => '<div class="alert alert-success">Data successfully created</div>']);
        } catch (\Throwable $th) {
            // error handle
            DB::rollBack();
            Log::info($th->getMessage());
            return redirect()->back()->with(['pesan' => '<div class="alert alert-danger">An error occurred, please try again</div>']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        // validate form
        $validator = JSvalidation::make([
            'code'  => 'required|unique:companies,company_code|min:1',
            'name'  => 'required|min:3',
        ]);

        // page
        return view('backend.company.edit', compact('validator', 'company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        // validate form
        $validasi = $request->validate([
            'code'  => 'required|min:1|unique:companies,company_code,' . $company->id,
            'name'  => 'required|min:3',
        ]);

        DB::beginTransaction();
        try {
            // update data
            Company::find($company->id)->update([
                'company_code' => $request->code,
                'company_name' => $request->name,
                'logo' => $request->foto,
                'user_update' => Auth::id(),
            ]);
            DB::commit();

            // create log
            Weblog::set('Update company name ' . $company->company_name . ' to ' . $request->name);

            // redirect index
            return redirect(route('company.index'))->with(['pesan' => '<div class="alert alert-success">Data successfully updated</div>']);
        } catch (\Throwable $th) {
            // error handle
            DB::rollBack();
            Log::warning($th->getMessage());
            return redirect()->back()->with(['pesan' => '<div class="alert alert-danger">An error occurred, please try again</div>']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        DB::beginTransaction();
        try {
            // delete
            $status = Company::find($company->id)->status;
            if ($status == 'y') {
                Company::find($company->id)->update([
                    'status' => 'n'
                ]);
                DB::commit();
                Weblog::set('Disable Company : ' . $company->company_name);

                return response()->json([
                    'tipe' => true,
                    'pesan' => 'Data successfully deleted'
                ]);
            } else {
                // activate
                Company::find($company->id)->update([
                    'status' => 'y'
                ]);
                DB::commit();
                Weblog::set('Activate Company : ' . $company->company_name);

                return response()->json([
                    'tipe' => true,
                    'pesan' => 'Data successfully reactivated'
                ]);
            }
        } catch (\Throwable $e) {
            DB::rollBack();
            return response()->json([
                'tipe' => false,
                'pesan' => $e->errorInfo,
            ]);
        }
    }

    public function ganti_foto(Request $request)
    {
        if ($request->has('file')) {
            $file = $request->file;

resources/views/backend/company/create.blade.php
@extends('backend.layouts.layout')

@section('konten')
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4">
                    <h5 class="card-header">Create company</h5>

                    <div class="card-body">
                        @if (session()->has('pesan'))
                            {!! session('pesan') !!}
                        @endif

                        <form action="{{ route('company.store')}}" method="POST" enctype="multipart/form-data" id="my-form">
                            @csrf
        
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="code">Code</label>
                                <div class="col-sm-9">
                                    <input type="number" class="form-control" name="code" value="{{ old("code") }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="name">Name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="name" value="{{ old("name") }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="foto">Logo</label>
                                <div class="col-sm-9">
                                    <div class="button-wrapper">
                                        <button type="button" class="account-file-input btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalUploadFoto">
                                            <span class="d-none d-sm-block">Choose photo</span>
                                            <i class="bx bx-upload d-block d-sm-none"></i>
                                        </button>
                                        <input type="hidden" name="foto" id="foto" value="">
                                        <div><small class="text-muted mb-0">Format : JPG, GIF, PNG. Maximum size 2000 Kb</small></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="email"></label>
                                <div class="col-sm-9">
                                    <div id="box-foto"></div>
                                </div>
                            </div>
        
                            <div class="row justify-content-end">
                                <div class="col-sm-9">
                                    <a href="{{ route('company.index')}}" class="btn btn-link btn-sm">Cancel</a>
                                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                                </div>
                            </div>
                        </form>

                    </div>
                    <!-- /Account -->
                </div>

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalUploadFoto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalUploadFotoLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalUploadFotoLabel">Upload Photo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span id="notif"></span>
                <form action="{{ route('company-ganti-foto') }}" class="dropzone" id="upload-image" method="POST" enctype="multipart/form-data">
                    @csrf
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-sm btn-simpan" onclick="simpanFoto()">Add</button>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}"></script>
    {!! $validator->selector('#my-form') !!}

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

    <script>
        Dropzone.options.uploadImage = {
            maxFilesize : 2000,
            acceptedFiles: ".jpeg,.jpg,.png",
            method : 'post',
            createImageThumbnails: true,
            init: function(){
                this.on("addedfile", file => {
                    $('.btn-simpan').attr('disabled','disabled').text('Loading...');
                });
            },
            success: function (file, response) {
                $('.btn-simpan').removeAttr('disabled').text('Add');
                const foto = response.file;
                $('.modal-body #notif').html(`<div class="alert alert-success">Photo successfully uploaded</div>`);
                $('#foto').val(foto);
            },
            error: function(file, response){
                $('.btn-simpan').removeAttr('disabled').text('Add');
                const pesan = response.message;
                $('.modal-body #notif').html(`<div class="alert alert-danger">${pesan}</div>`);
            }
        };

        function simpanFoto(){
            let foto = $('#foto').val();

            if(foto === '' || foto === null){
                $('#notif').html(`<div class="alert alert-danger">Unable to add photo</div>`);
            }else{
                $('#modalUploadFoto').modal('hide');
                $('#box-foto').html(`<img src="{{ url('/storage/company/thum_${foto}') }}" class="rounded">`);
            }
        }
    </script>
@endsection

resources/views/backend/company/edit.blade.php
@extends('backend.layouts.layout')

@section('konten')
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4">
                    <h5 class="card-header">Edit Company</h5>
                    <div class="card-body">
                        @if (session()->has('pesan'))
                            {!! session('pesan') !!}
                        @endif

                        <form action="{{ route('company.update', ['company' => $company->id]) }}" method="POST" enctype="multipart/form-data" id="my-form">
                            @csrf
                            @method('PATCH')

                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="code">Code</label>
                                <div class="col-sm-9">
                                    <input type="number" class="form-control" name="code" value="{{ old("code", $company->company_code) }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="name">Name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="name" value="{{ old("name", $company->company_name) }}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="email">Logo</label>
                                <div class="col-sm-9">
                                    <div class="button-wrapper">
                                        <button type="button" class="account-file-input btn btn-sm btn-outline-primary"
                                            data-bs-toggle="modal" data-bs-target="#modalUploadFoto">
                                            <span class="d-none d-sm-block">Change photo</span>
                                            <i class="bx bx-upload d-block d-sm-none"></i>
                                        </button>
                                        <input type="hidden" name="foto" id="foto" value="{{ $company->logo }}">
                                        <div><small class="text-muted mb-0">Format : JPG, GIF, PNG. Maximum size 2000 Kb
                                                Kb</small></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-3 col-form-label" for="email"></label>
                                <div class="col-sm-9">
                                    <div id="box-foto">
                                        @if ($company->logo)
                                            <img src="{{ url('/storage/company/thum_' . $company->logo) }}" class="rounded">
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row justify-content-end">
                                <div class="col-sm-9">
                                    <a href="{{ route('company.index') }}" class="btn btn-link btn-sm">Cancel</a>
                                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                                </div>
                            </div>
                        </form>

                    </div>
                    <!-- /Account -->
                </div>

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalUploadFoto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalUploadFotoLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalUploadFotoLabel">Upload Photo</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <span id="notif"></span>
                    <form action="{{ route('company-ganti-foto') }}" class="dropzone" id="upload-image" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-sm btn-simpan"
                        onclick="simpanFoto()">Add</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}"></script>
    {!! $validator->selector('#my-form') !!}

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

    <script>
        Dropzone.options.uploadImage = {
            maxFilesize: 2000,
            acceptedFiles: ".jpeg,.jpg,.png",
            method: 'post',
            createImageThumbnails: true,
            init: function() {
                this.on("addedfile", file => {
                    $('.btn-simpan').attr('disabled', 'disabled').text('Loading...');
                });
            },
            success: function(file, response) {
                $('.btn-simpan').removeAttr('disabled').text('Add');
                const foto = response.file;
                $('.modal-body #notif').html(`<div class="alert alert-success">Photo successfully uploaded</div>`);
                $('#foto').val(foto);
            },
            error: function(file, response) {
                $('.btn-simpan').removeAttr('disabled').text('Add');
                const pesan = response.message;
                $('.modal-body #notif').html(`<div class="alert alert-danger">${pesan}</div>`);
            }
        };

        function simpanFoto() {
            let foto = $('#foto').val();

            if (foto === '' || foto === null) {
                $('#notif').html(`<div class="alert alert-danger">Unable to add photo</div>`);
            } else {
                $('#modalUploadFoto').modal('hide');
                $('#box-foto').html(`<img src="{{ url('/storage/company/thum_${foto}') }}" class="rounded">`);
            }
        }
    </script>
@endsection

resources/views/backend/company/export.blade.php
<table>
    <thead>
        <tr>
            <th><b>NO</b></th>
            <th><b>COMPANY CODE</b></th>
            <th><b>COMPANY NAME</b></th>
            <th><b>TIME INPUT</b></th>
            <th><b>USER INPUT</b></th>
            <th><b>LAST UPDATE</b></th>
            <th><b>USER UPDATE</b></th>
        </tr>
    </thead>
    <tbody>
        @php
            $no=1;
        @endphp
        @foreach ($data as $item)
        <tr>
            <td align="center">{{ $no++ }}</td>
            <td>{{ $item->company_code }}</td>
            <td>{{ $item->company_name }}</td>
            <td>{{ $item->time_input }}</td>
            <td>{{ $item->userinput->nama }}</td>
            <td>{{ ($item->time_update == null) ? '-' : $item->time_update }}</td>
            <td>{{ ($item->userupdate == null) ? '-' : $item->userupdate->nama }}</td>
        @endforeach
    </tbody>
</table>